### ISSUE TITLE
Bug: Compilation or Execution error found while running `QuestCore2.db`

### ISSUE THREAD

**Issue by rdaum** [rdaum/moor#23]
Problem in stack unwinding related to error Catch handling.

Found while running:
`help $scheduler`

Doesn't happen for other `:help_msg` invocations it seems.  Haven't tracked down what verb flow is causing this yet.

daemon log:

```
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-09-24T21:59:30.157150364Z 2023-09-24T21:59:30.156994Z  WARN ThreadId(15) do_process: crates/kernel/src/tasks/scheduler.rs:787: Task sys-errored task=69 error=Disconnected
2023-09-24T22:00:42.543329425Z thread 'tokio-runtime-worker' panicked at 'TODO: CatchLabel where we didn't expect it...', crates/kernel/src/vm/vm_unwind.rs:367:25
2023-09-24T22:00:42.543368941Z stack backtrace:
2023-09-24T22:00:42.543373580Z    0: rust_begin_unwind
2023-09-24T22:00:42.543376937Z              at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
2023-09-24T22:00:42.543380263Z    1: core::panicking::panic_fmt
2023-09-24T22:00:42.543383389Z              at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
2023-09-24T22:00:42.543388429Z    2: moor_kernel::vm::vm_unwind::<impl moor_kernel::vm::VM>::unwind_stack
2023-09-24T22:00:42.543392156Z              at ./crates/kernel/src/vm/vm_unwind.rs:367:25
2023-09-24T22:00:42.543410261Z    3: moor_kernel::vm::vm_execute::<impl moor_kernel::vm::VM>::exec::{{closure}}
2023-09-24T22:00:42.543413777Z              at ./crates/kernel/src/vm/vm_execute.rs:502:28
2023-09-24T22:00:42.543446871Z    4: <moor_kernel::tasks::moo_vm_host::MooVmHost as moor_kernel::tasks::vm_host::VMHost<moor_kernel::vm::opcode::Program>>::exec_interpreter::{{closure}}
2023-09-24T22:00:42.543462882Z              at ./crates/kernel/src/tasks/moo_vm_host.rs:182:68
```

**Comment by rdaum** [comment]
```
2023-09-25T00:47:07.905280Z DEBUG ThreadId(05) task_run: crates/kernel/src/vm/vm_call.rs:245: Calling builtin: eval("this=#59;; return \"Written by Firesong (#337)@Weyrmount\";;") caller_perms: #2
2023-09-25T00:47:07.906286169Z 2023-09-25T00:47:07.906213Z DEBUG ThreadId(05) task_run: crates/kernel/src/vm/vm_unwind.rs:308: unwind_stack why=Return("Written by Firesong (#337)@Weyrmount") this=Objid(2) from="eval" line=2
2023-09-25T00:47:07.906320537Z 2023-09-25T00:47:07.906276Z DEBUG ThreadId(05) task_run: crates/kernel/src/vm/vm_unwind.rs:308: unwind_stack why=Return({1, "Written by Firesong (#337)@Weyrmount"}) this=Objid(-1) from="eval" line=0
2023-09-25T00:47:07.906369032Z 2023-09-25T00:47:07.906315Z DEBUG ThreadId(05) task_run: crates/kernel/src/vm/vm_unwind.rs:308: unwind_stack why=Return({1, "Written by Firesong (#337)@Weyrmount"}) this=Objid(38) from="eval" line=13
2023-09-25T00:47:07.906415894Z 2023-09-25T00:47:07.906378Z DEBUG ThreadId(05) task_run: crates/kernel/src/vm/vm_call.rs:245: Calling builtin: match("info = this:get_task_display();", "^\"%([^\\\"]%|\\.%)*\";$") caller_perms: #2
2023-09-25T00:47:07.906470551Z 2023-09-25T00:47:07.906427Z DEBUG ThreadId(05) task_run: crates/kernel/src/vm/vm_unwind.rs:308: unwind_stack why=Return({}) this=Objid(-1) from="match" line=0
2023-09-25T00:47:07.906566138Z 2023-09-25T00:47:07.906468Z DEBUG ThreadId(05) task_run: crates/kernel/src/vm/vm_unwind.rs:308: unwind_stack why=Return({":@sched*uler()   <-- A Feature Verb to diplay an alternate task list on the scheduler.", "", "Sample output:", "", "[SCHEDULER] Browse Mode", "", "The Scheduler is currently ticking away", "  Tasks waiting in queue : 31", "  Current system time    : Tue Apr  9 18:38:09 1996 HDT", "", "                                                                   Running in..", "-------------------------------------------------------------------------------", "Verb  : #280:DO_check_kids()                                          8 seconds", "Perms : Firesong (#337)                           Task ID : 1300241341", "Player: Firesong (#337)                           Interval: 60 seconds", "-------------------------------------------------------------------------------", "Done..", "", "Written by Firesong (#337)@Weyrmount"}) this=Objid(59) from="verb_documentation" line=17
2023-09-25T00:47:07.906584174Z thread 'tokio-runtime-worker' panicked at 'TODO: CatchLabel where we didn't expect it...', crates/kernel/src/vm/vm_unwind.rs:367:25
2023-09-25T00:47:07.906613251Z stack backtrace:
```

**Comment by rdaum** [comment]
Last executed code being the return @ line 17 from here:
```
 1:  ":verb_documentation([object,verbname]) => documentation at beginning of verb code, if any";
 2:  "default is the calling verb";
 3:  set_task_perms(caller_perms());
 4:  c = callers()[1];
 5:  {?object = c[4], ?vname = c[2]} = args;
 6:  try
 7:      code = verb_code(object, vname);
 8:  except error (ANY)
 9:      return error[2];
10:  endtry
11:  doc = {};
12:  for line in (code)
13:      if (match(line, "^\"%([^\\\"]%|\\.%)*\";$"))
14:          "... now that we're sure `line' is just a string, eval() is safe...";
15:          doc = {@doc, $no_one:eval("; return " + line)[2]};
16:      else
17:          return doc;
18:      endif
19:  endfor
20:  return doc;
```

**Comment by rdaum** [comment]
Can reproduce with this limited block code. Something to do with `try` blocks followed by a loop with a return inside.

```
 1:  try
 2:      player:tell(5);
 3:  except error (ANY)
 4:      return 1;
 5:  endtry
 6:  for x in ({1, 2, 3})
 7:      player:tell(x);
 8:      return 5;
 9:  endfor
 ```
